name: Linters

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - name: Run prettier
        run: |
          ./dev.sh npm ci
          ./dev.sh npm run format
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: prettier
          fail_on_error: true

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run eslint
        run: |
          ./dev.sh npm ci
          ./dev.sh npm run lint
