name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Publishing release assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./build.sh
      - name: Attach Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tar czf ns8-user-manager-${{ github.event.release.tag_name }}.tar.gz -C dist .
          gh release upload ${{ github.event.release.tag_name }} ns8-user-manager-${{ github.event.release.tag_name }}.tar.gz
