name: Release Please

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-please'))
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./build.sh
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      - name: Attach Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tar czf ns8-user-manager-${{ steps.release.outputs.tag_name }}.tar.gz -C dist .
          gh release upload ${{ steps.release.outputs.tag_name }} ns8-user-manager-${{ steps.release.outputs.tag_name }}.tar.gz
