name: Release Please

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./build.sh
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: ns8-user-manager
      - name: Attach Release
        if: ${{ steps.release.outputs.release_created }}
        run:
          mv dist ns8-user-manager-${{ steps.release.outputs.tag_name }}
          gh release upload ${{ steps.release.outputs.tag_name }} ns8-user-manager-${{ steps.release.outputs.tag_name }}
